### ISSUE TITLE
FR: Automatic choose of Quest Dialogs / German Translation

### ISSUE THREAD

**Issue by pthoelken** [lure/AutoTurnIn#12]
Hi, what do you think about the feature that ATI automatically choose the right dialog from the quest-npc if it's needed? Like the picture below: 

![image](https://user-images.githubusercontent.com/12643853/102710706-763a2280-42b4-11eb-98a0-0b44c3f5f341.png)

And I've optimized the german language file for the german-spelling. Do you need this? Should I make a PR? :-)

**Comment by lure** [comment]
Intresting option, ty. Not sure when I have time to make it.

**Comment by xan2622** [comment]
I second this request.

**Comment by lure** [comment]
@pthoelken  
Sorry, I just realized you made a fix for german translation. IF you still have it by any change, would you kindly make a PR? 
Thank you.
