### ISSUE TITLE
Text misalignement on the Quest Window when AutoTurnIn and ElvUI are activated

### ISSUE THREAD

**Issue by xan2622** [lure/AutoTurnIn#14]
Hi.

I noticed a small "quest objectives text misalignement" on the Quest window when both **ElVUI 12.24** and **AutoTurnIn 9.0.2** are activated.

Here is the default Blizzard Quest Window, with all addons disabled (as you can see, there's no problem): 

![defaultUI_QUEST](https://user-images.githubusercontent.com/1732773/117606528-58cdfe00-b15a-11eb-8ca4-bb200fcfc6b8.jpg)

Note that this default Quest Window looks the same when only **AutoTurnIn 9.0.2** is enabled (all quests objectives look fine, the quest window looks the same as the above screenshot).

---

Here is the Quest Window when only **ElvUI 12.24** is enabled (no misalignement, quests objectives look fine): 

![Only_ElvUI_QUEST](https://user-images.githubusercontent.com/1732773/117607286-f0801c00-b15b-11eb-8939-a443e56c956b.jpg)

---

But when both **ElvUI 12.24** and **AutoTurnIn 9.0.2** are activated, here is how the Quest Window looks like: 

![ElvUI_QUEST](https://user-images.githubusercontent.com/1732773/117606712-bd895880-b15a-11eb-9946-4ae926d0b38a.jpg)

---

_World of Warcraft Shawdowlands version 9.0.5.38134
French locale (it may also happen with other languages, I don't know)_
Windows 10 64bits, nvidia GTX 1070 (drivers: 465.89)

**Comment by lure** [comment]
@xan2622  
Sorry, I got no notification for this message. 
I regret to say that I am not going to investigate this issue, for a simple reason: there are hundreds of different UI and I have no resources to adjust the addon to them. 
You may want to remove the tick from the "show quest level" option.
