### ISSUE TITLE
Move the "Ignore this NPC" checkbox

### ISSUE THREAD

**Issue by jjholleman** [lure/AutoTurnIn#15]
When an NPC has a reputation bar on the GossipFrame, the checkbox is very hard to see and click on. 
My suggestion is to move the checkbox and text on top of the GossipFrame, above the NPC name.

![image](https://user-images.githubusercontent.com/6916881/124383354-53a9ad00-dccc-11eb-8728-803f899d8632.png)

**Comment by gaveer** [comment]
@lure  i have the same issue for a long time , i adject the placment of ignore box on : AutoTurnIn.lua  @ Line **934**
```
IgnoreButton:SetPoint("TOPLEFT", 90, -18)
```
![image](https://user-images.githubusercontent.com/45834601/157639133-e3ec1e42-61c8-41df-ad26-07de1b9bc1dd.png)
