### ISSUE TITLE
Error when going into edit mode

### ISSUE THREAD

**Issue by marklabrecque** [lure/AutoTurnIn#22]
![image](https://user-images.githubusercontent.com/16848211/198845727-236f938d-7af7-41be-bf85-5e569cef558d.png)

If there is a way I can access the error log to provide more details on this error, please let me know how to do so and I will attach it to this issue.

Thanks!

**Comment by marklabrecque** [comment]
This actually appears in other cases as well, I am noticing

**Comment by lure** [comment]
fixed in 10.0.5
